print("HELLO")

#multiline comments  three quotations
"""
multi 
line 
comments
"""
#variable  it ia a container for storing data values
x=10
y="hii"
print(x)
print(type(y))


#type conversion 
#to integer,float,string,boolean,list,tuple,set
x = 45.14
a = int(x)  
print(a)

x = 5
b = float(x)  
print(b)

x = 100
s = str(x)  
print(s)

x = 0
c = bool(x)  
print(c)

s = [1,2,3,109,22]
t = tuple(s)  
print(s)

l = [1,2,2,3]
s = set(l)  
print(l)

#keywords 
#and,break,continue,def,else,except,for,if,in,or,not,return,while etc 

